# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: loucas papantoniou
subtitle: EMPATHETIC, CURIOUS &amp; FRIENDLY.
email: loucaspapa@gmail.com
description: UX Designer at Central. Leading design sprints, prototyping and testing, helping the team to continue creating thoughtfully considered digital interfaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://loucaspapa.org" # the base hostname & protocol for your site
twitter_username: follow me
central_url: "http://central.team/"

# Build settings
markdown: kramdown

# posts permalink
permalink: /posts/:title/

# Collections
collections:
  work:
    output: true
    permalink: /work/:title/

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      currentNav: posts
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: work
      currentNav: work
