# Site settings
title: "loucas<span class='hidden-xs'> <span>papa<span class='hidden-xs'>ntoniou</span>"
subtitle: EMPATHETIC, CURIOUS &amp; FRIENDLY.
email: loucaspapa@gmail.com
description: "Product designer at Central; not a rockstar, a unicorn, a ninja or a magician. Design is for me a sense-making process in creating thoughtfully considered digital interfaces."
# It's not about ideal solutions, but about the best possible compromises. There is too much clutter and bullshit in the world, so lets please avoid littering it with moreâ€¦
baseurl: "" # the subpath of your site, e.g. /blog
url: "loucaspapa.org" # the base hostname & protocol for your site
twitter_username: "follow me"
central_url: "http://central.team/"

# Build settings
markdown: kramdown
exclude: [/node_modules]

# posts permalink
permalink: /posts/:title/

# Collections
collections:
  work:
    output: true
    permalink: /work/:title/
  notes:

# Defaults front matter variables for various types
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      currentNav: posts
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: work
      currentNav: work
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: note
      currentNav: notes
